version: 2
jobs:
  lint:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn lint
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn test
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test
      - build
